name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          flutter-version: '3.19.0'
      
      - name: Enable Web
        run: flutter config --enable-web
        
      - name: Get dependencies
        run: flutter pub get
        
      - name: Build
        run: flutter build web --base-href "/rebalancingcalculator_seng/"

      - name: Create .nojekyll file
        run: touch ./build/web/.nojekyll

      - name: Copy to docs folder
        run: |
          rm -rf docs
          cp -r build/web docs

      - name: Commit and push changes
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git add docs
          git commit -m "Update docs folder"
          git push 